# Generated by Django 3.1.1 on 2020-09-08 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=128)),
                ('register_time', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('desciption', models.CharField(max_length=2048)),
                ('created_time', models.IntegerField()),
                ('borrowed_time', models.IntegerField(null=True)),
                ('borrower_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orrower_id', to=settings.AUTH_USER_MODEL)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceApply',
            fields=[
                ('apply_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('apply_time', models.IntegerField()),
                ('handle_time', models.IntegerField()),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DeviceApply_applicant_id', to=settings.AUTH_USER_MODEL)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DeviceApply_device_id', to='webservice.device')),
                ('handler_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DeviceApply_handler_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreateApply',
            fields=[
                ('apply_id', models.IntegerField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=256)),
                ('device_desciption', models.CharField(max_length=2048)),
                ('status', models.IntegerField()),
                ('apply_time', models.IntegerField()),
                ('handle_time', models.IntegerField()),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CreateApply_applicant_id', to=settings.AUTH_USER_MODEL)),
                ('handler_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CreateApply_handler_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
