# Generated by Django 3.1.1 on 2020-09-09 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=128)),
                ('register_time', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivateCode',
            fields=[
                ('code_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('expired_time', models.DateTimeField()),
                ('code', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('desciption', models.CharField(max_length=2048)),
                ('created_time', models.IntegerField()),
                ('borrowed_time', models.IntegerField(null=True)),
                ('return_time', models.IntegerField(null=True)),
                ('borrower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orrower', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PermApply',
            fields=[
                ('apply_id', models.IntegerField(primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=256)),
                ('status', models.IntegerField()),
                ('apply_time', models.IntegerField()),
                ('handle_time', models.IntegerField(null=True)),
                ('reason', models.TextField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PermApply_applicant', to=settings.AUTH_USER_MODEL)),
                ('handler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PermApply_handler', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceApply',
            fields=[
                ('apply_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('apply_time', models.IntegerField()),
                ('handle_time', models.IntegerField(null=True)),
                ('reason', models.TextField()),
                ('return_time', models.IntegerField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DeviceApply_applicant', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DeviceApply_device', to='webservice.device')),
                ('device_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DeviceApply_device_owner', to=settings.AUTH_USER_MODEL)),
                ('handler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DeviceApply_handler', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreateApply',
            fields=[
                ('apply_id', models.IntegerField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=256)),
                ('device_description', models.CharField(max_length=2048)),
                ('status', models.IntegerField()),
                ('apply_time', models.IntegerField()),
                ('handle_time', models.IntegerField(null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CreateApply_applicant', to=settings.AUTH_USER_MODEL)),
                ('handler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CreateApply_handler', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_time', models.BigIntegerField()),
                ('content', models.TextField()),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webservice.device')),
            ],
        ),
    ]
