# Generated by Django 3.1.1 on 2020-09-08 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('desciption', models.CharField(max_length=2048)),
                ('created_time', models.IntegerField()),
                ('borrowed_time', models.IntegerField(null=True)),
                ('borrower_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orrower_id', to=settings.AUTH_USER_MODEL)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
